### ISSUE TITLE
[Request] Additional Apps to Update

### ISSUE THREAD

**Issue by Exophobias** [v3DJG6GL/truecharts_archive#1]
Hi there! I found your fork of the archive and I like most of what you are updating. I am wondering if you would be willing to add the following updates to your repository even though you do not use them. It would be greatly appreciated for my media setup and possibly others who find this fork.
- Plex
- Overseerr
- Tautulli
- SABnzbd

If not, that is all good. Just wanted to at least shoot my shot and ask.

Appreciate the updates!
Thanks

**Comment by v3DJG6GL** [comment]
Hi @Exophobias 
I've just updated these applications:

- Plex: v1.40.4.8679
- SABnzbd: v4.3.2
- Tautulli: v2.14.3
- Overseerr: Hasn't received an update since July 2023, so no update for this app ;)

**Comment by Exophobias** [comment]
Appreciate it!

**Comment by m-aar-ten** [comment]
Hello,

Would it be possible to add updates for:
Paperless-ngx
Syncthing

If not that's fine.
Thank you anyways for all the updates you pushed so far, it has been such a blessing!

**Comment by v3DJG6GL** [comment]
@m-aar-ten
Done:

- **Paperless-ngx** has been updated to **v2.11.3**
- **Syncthing** has been updated to **v1.27.10**

Beware: I haven't checked their functionality since I don't use them. So always backup your data before updating!

**Comment by mivlives4ever** [comment]
Hi v3DJG6GL,

Can you also update:

Nzbget

Please? and thanks for updating the other apps too!

**Comment by v3DJG6GL** [comment]
Hi @mivlives4ever 

- NZBGet: Hasn't received an update may, so no update for this app ;)

**Comment by Niborian** [comment]
Hi there,

Could you please update Maintainerr and Bazarr?

Also, I tried installing the Factorio server but ran into a version mismatch. I managed to fix it by updating the image tag from:

```yaml
image:
  pullPolicy: IfNotPresent
  repository: factoriotools/factorio
  tag: stable@sha256:fae8a40742bd6fc42c92eac3956ad36737cf0ce5a31d2793438b65ad8b50d50a
```
to:

```yaml
image:
  pullPolicy: IfNotPresent
  repository: factoriotools/factorio
  tag: stable
```
To do this, I duplicated the old folder, changed the version numbers (e.g., from 8.0.9 to 8.1.0), and adjusted the app versions accordingly.

Is there any reason not to use the "stable" tag like this? I’ve technically updated Maintainerr as well, but I can’t update it in TrueNAS since it’s linked to the TrueCharts catalog. I’m hesitant to set it up again from scratch.

If what I did isn’t the best approach, I’d love to learn more and help out if you’d allow me! 😊
