### ISSUE TITLE
[ISSUE] codeproject-ai-server incorrect app version

### ISSUE THREAD

**Issue by rudi-mueller** [v3DJG6GL/truecharts_archive#26]
App version in `Chart.yaml` ,  `catalog.json` and `app_versions.json` is showing the application versions as 2.5.1, eg:

```
        "codeproject-ai-server": {
            <snip>
            "home": "https://truecharts.org/charts/stable/codeproject-ai-server",
            "location": "/home/runner/_work/catalog/catalog/stable/codeproject-ai-server",
            "latest_version": "3.1.9",
            "latest_app_version": "2.5.1",
            "latest_human_version": "2.5.1_3.1.9",
            "last_update": "2024-05-29 12:35:14",
            "name": "codeproject-ai-server",
            "recommended": false,
            "title": "Codeproject-ai-server",
            "maintainers": [
```

whereas the image being used from `ix-values.yaml` is actually v2.6.5

```
image:
  pullPolicy: IfNotPresent
  repository: codeproject/ai-server
  tag: cpu-2.6.5@sha256:181c85af30bb464a1ad5db396ba0803ec82d9f912e54ff751f171f3342d27489
```
